"""Add licordata

Revision ID: 004830fc7f16
Revises: 2f8188f988e1
Create Date: 2023-11-29 15:06:56.891581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '004830fc7f16'
down_revision: Union[str, None] = '2f8188f988e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licordata',
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_licordata_created_at'), 'licordata', ['created_at'], unique=False)
    op.create_index(op.f('ix_licordata_description'), 'licordata', ['description'], unique=False)
    op.create_index(op.f('ix_licordata_id'), 'licordata', ['id'], unique=False)
    op.create_index(op.f('ix_licordata_iterator'), 'licordata', ['iterator'], unique=False)
    op.create_index(op.f('ix_licordata_name'), 'licordata', ['name'], unique=False)
    op.create_index(op.f('ix_licordata_recorded_at'), 'licordata', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licordata_recorded_at'), table_name='licordata')
    op.drop_index(op.f('ix_licordata_name'), table_name='licordata')
    op.drop_index(op.f('ix_licordata_iterator'), table_name='licordata')
    op.drop_index(op.f('ix_licordata_id'), table_name='licordata')
    op.drop_index(op.f('ix_licordata_description'), table_name='licordata')
    op.drop_index(op.f('ix_licordata_created_at'), table_name='licordata')
    op.drop_table('licordata')
    # ### end Alembic commands ###
