"""Add licordata relation to sites

Revision ID: 0307ae7d584f
Revises: 004830fc7f16
Create Date: 2023-11-30 16:07:34.862093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0307ae7d584f'
down_revision: Union[str, None] = '004830fc7f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licordata', sa.Column('site_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_licordata_site_id'), 'licordata', ['site_id'], unique=False)
    op.create_foreign_key(None, 'licordata', 'site', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'licordata', type_='foreignkey')
    op.drop_index(op.f('ix_licordata_site_id'), table_name='licordata')
    op.drop_column('licordata', 'site_id')
    # ### end Alembic commands ###
