"""Add location

Revision ID: 1bb697b163b3
Revises: b24090722a77
Create Date: 2023-11-27 16:26:44.969253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1bb697b163b3'
down_revision: Union[str, None] = 'b24090722a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_site_location'), 'site', ['location'], unique=False)
    op.create_foreign_key(None, 'site', 'fieldcampaign', ['field_campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='foreignkey')
    op.drop_index(op.f('ix_site_location'), table_name='site')
    op.drop_column('site', 'location')
    # ### end Alembic commands ###
