"""Allow description nullable

Revision ID: 2f8188f988e1
Revises: 787a9f5289cc
Create Date: 2023-11-29 10:14:15.311332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f8188f988e1'
down_revision: Union[str, None] = '787a9f5289cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_site_description'), 'site', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_description'), table_name='site')
    op.alter_column('site', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
